<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Marketplace.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marketplace.Business\Marketplace.Business.csproj" />
    <ProjectReference Include="..\Marketplace.Data\Marketplace.Data.csproj" />
  </ItemGroup>

</Project>
